// <auto-generated />
using AuctionHunterFront.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace AuctionHunterFront.Migrations.AuctionHunterDb
{
    [DbContext(typeof(AuctionHunterDbContext))]
    partial class AuctionHunterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("AuctionHunterFront.Models.ApplicationUserAuctionHunterItem", b =>
                {
                    b.Property<string>("ApplicationUserId");

                    b.Property<int>("AuctionHunterItemId");

                    b.HasKey("ApplicationUserId", "AuctionHunterItemId");

                    b.HasIndex("AuctionHunterItemId");

                    b.ToTable("ApplicationUserAuctionHunterItems");
                });

            modelBuilder.Entity("AuctionHunterFront.Models.AuctionHunterItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AuctionLink")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("ContentJson");

                    b.Property<int>("OnPage");

                    b.Property<DateTime>("Timestamp");

                    b.HasKey("Id");

                    b.HasIndex("AuctionLink")
                        .IsUnique();

                    b.ToTable("AuctionHunterItems");
                });

            modelBuilder.Entity("AuctionHunterFront.Models.ApplicationUserAuctionHunterItem", b =>
                {
                    b.HasOne("AuctionHunterFront.Models.AuctionHunterItem", "AuctionHunterItem")
                        .WithMany()
                        .HasForeignKey("AuctionHunterItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
