// <auto-generated />
using AuctionHunterFront.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace AuctionHunterFront.Migrations
{
    [DbContext(typeof(AuctionHunterDbContext))]
    [Migration("20180217023448_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("AuctionHunterFront.Models.AuctionHunterItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AdditionalDataJson");

                    b.Property<string>("AuctionLink");

                    b.Property<bool>("MarkedAsRead");

                    b.Property<int>("OnPage");

                    b.Property<DateTime>("Timestamp");

                    b.HasKey("ID");

                    b.ToTable("AuctionHunterItems");
                });
#pragma warning restore 612, 618
        }
    }
}
